spring:
  application:
    name: crypto-ticker-server

  datasource:
    url: jdbc:postgresql://localhost:5432/pixelcore75
    username: pixelcore75
    password: difficultpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      leak-detection-threshold: 10000
      max-lifetime: 1800000
      keepalive-time: 300000

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-missing-creator-properties: true
      fail-on-null-creator-properties: true
      fail-on-invalid-subtype: true
    mapper:
      accept-case-insensitive-properties: false

logging:
  level:
    root: INFO

pixelcore75:
  crypto:
    client: coingecko
    apikey: ${CRYPTO_API_KEY:}
    currency: euro
  soccer:
    client: espn
    apikey: ${SOCCER_API_KEY:}
    basePath: https://sports.core.api.espn.com/v2/sports/

  jwt:
    secret: my-access-secret-change-me-my-access-secret-change-me
    refresh-secret: my-refresh-secret-change-me-my-refresh-secret-change-me
    access-expiration: 7200000     # 2 HRS
    refresh-expiration: 604800000 # 7 days